# Generated by Django 4.1.3 on 2022-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('adresseMail', models.EmailField(max_length=40)),
                ('motDePase', models.CharField(max_length=60)),
                ('recevoirMail', models.BooleanField()),
                ('cgu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.IntegerField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('titreOriginal', models.CharField(max_length=100)),
                ('bandeAnnonce', models.CharField(max_length=100)),
                ('popularite', models.FloatField()),
                ('affiche', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('nombreSaison', models.IntegerField(max_length=10)),
                ('nombreEpisodes', models.IntegerField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('dureeMoyEp', models.IntegerField(max_length=10)),
                ('listActeur', models.ManyToManyField(through='appliWNR.Role', to='appliWNR.acteur')),
                ('listCompaProd', models.ManyToManyField(to='appliWNR.compagnieproduction')),
                ('listGenre', models.ManyToManyField(to='appliWNR.genre')),
                ('listRealisateur', models.ManyToManyField(to='appliWNR.realisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('titreOriginal', models.CharField(max_length=100)),
                ('bandeAnnonce', models.CharField(max_length=100)),
                ('popularite', models.FloatField()),
                ('affiche', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('listActeur', models.ManyToManyField(through='appliWNR.Role', to='appliWNR.acteur')),
                ('listCompaProd', models.ManyToManyField(to='appliWNR.compagnieproduction')),
                ('listGenre', models.ManyToManyField(to='appliWNR.genre')),
                ('listRealisateur', models.ManyToManyField(to='appliWNR.realisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
