# Generated by Django 4.1.3 on 2023-01-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('titreOriginal', models.CharField(max_length=100)),
                ('bandeAnnonce', models.CharField(max_length=100)),
                ('popularite', models.FloatField()),
                ('affiche', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliWNR.acteur')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliWNR.film')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('adresseMail', models.EmailField(max_length=40)),
                ('motDePase', models.CharField(max_length=60)),
                ('recevoirMail', models.BooleanField()),
                ('cgu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('titreOriginal', models.CharField(max_length=100)),
                ('bandeAnnonce', models.CharField(max_length=100)),
                ('popularite', models.FloatField()),
                ('affiche', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('nombreSaison', models.IntegerField(default=1)),
                ('nombreEpisodes', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=100)),
                ('dureeMoyEp', models.IntegerField()),
                ('listActeur', models.ManyToManyField(through='appliWNR.Role', to='appliWNR.acteur')),
                ('listCompaProd', models.ManyToManyField(to='appliWNR.compagnieproduction')),
                ('listGenre', models.ManyToManyField(to='appliWNR.genre')),
                ('listRealisateur', models.ManyToManyField(to='appliWNR.realisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliWNR.serie'),
        ),
        migrations.AddField(
            model_name='film',
            name='listActeur',
            field=models.ManyToManyField(through='appliWNR.Role', to='appliWNR.acteur'),
        ),
        migrations.AddField(
            model_name='film',
            name='listCompaProd',
            field=models.ManyToManyField(to='appliWNR.compagnieproduction'),
        ),
        migrations.AddField(
            model_name='film',
            name='listGenre',
            field=models.ManyToManyField(to='appliWNR.genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='listRealisateur',
            field=models.ManyToManyField(to='appliWNR.realisateur'),
        ),
    ]
