# Generated by Django 4.1.2 on 2022-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appliWNR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="affiche",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
