# Generated by Django 4.1.4 on 2023-01-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('utilisateur', 'programme')},
        ),
    ]
