# Generated by Django 4.1.4 on 2023-01-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0002_alter_note_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maliste',
            old_name='programme',
            new_name='programmes',
        ),
    ]
