# Generated by Django 4.1.4 on 2023-01-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0003_rename_programme_maliste_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listesuggestion',
            name='derniereMAJ',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
