# Generated by Django 4.1.4 on 2023-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0004_listesuggestion_dernieremaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.IntegerField(),
        ),
    ]
