# Generated by Django 4.1.4 on 2023-01-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0006_alter_note_unique_together_note_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('utilisateur', 'programme')},
        ),
    ]
