# Generated by Django 4.1.4 on 2023-01-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0007_alter_note_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliWNR.programme'),
        ),
        migrations.AlterField(
            model_name='note',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
