# Generated by Django 4.1.4 on 2023-01-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0008_alter_note_programme_alter_note_utilisateur'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique',
        ),
    ]
