# Generated by Django 4.1.4 on 2023-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliWNR', '0013_alter_programme_titre_alter_programme_titreoriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnieproduction',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plateforme',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
